@startuml Main

[data-extraction] 
[webview]
[extension]

[webview] ..> [extension]: "Uses RPC contracts, connects using websockets"
[extension] ..> [webview]: "Loads into a Webview in VS Code"

[extension] ..> [data-extraction]: "Injects Runtime into JavaScript applications"

[webview] ..> [data-extraction]: "Uses common types"

@enduml